version: '3'

services:
  map-db:
    image: mysql:8.0.18
    container_name: map-db
    restart: "no"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mapeamento
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  map-api:
    image: python:3.8
    container_name: map-api
    restart: "no"
    working_dir: /usr/src/app
    command: bash -c "mkdir -p logs && pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      PYTHONUNBUFFERED: 1
      MYSQL:
      API_URL: 'http://localhost:8000'
      SITE_URL: 'http://localhost:3000'
      ALLOWED_HOST: 'localhost'
      DB_HOST: map-db
      DB_PASSWORD: root
      SES_USER:
      SES_PASSWORD:
      NEWSAPI_KEY:
      AIRTABLE_KEY: ${AIRTABLE_KEY:?AIRTABLE_KEY}
      AIRTABLE_URL: 'https://api.airtable.com/v0/appZTHHAAMqj1gs0E/'
    ports:
      - "8000:8000"
      - "34404:34404"
    volumes:
      - .:/usr/src/app
      - api-dependencies:/usr/local/lib/python3.8/site-packages
    links:
    - map-db
    depends_on:
    - map-db

volumes:
  db-data:
  api-dependencies: